require("core.option")
require("plugins.plugins-setup")
require("core.keymaps")

require("plugins.catppuccin")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.noice")
require("plugins.gitsigns")
require("core.lsp")