require("core.option")
require("plugins.plugins-setup")
require("core.keymaps")

require("plugins.treesitter")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.autosave")
require("plugins.ibl")
